### ISSUE TITLE
It doesn't work for me.

### ISSUE THREAD

**Issue by ST9527** [gzhappysky/sentry-dingtalk#1]
I am using Sentry docker v8.18.0. I exec into sentry's container, clone this project and `python setup.py install ` the package.Because I can't `pip install it !` . And I config the docker by adding this 

``` python
from sentry.conf.server import *
INSTALLED_APPS += (sentry_dingtalk, )
from sentry.plugins import register
from sentry_dingtalk.plugin import DingtalkPlugin
register(DingtalkPlugin)
```

to **sentry.conf.py** . So I can make it show up in the web.
But after I config it , It's would't send me a message when some error shows up.
What am I missing ?

**Comment by gzhappysky** [comment]
setup:

> git clone https://github.com/gzhappysky/sentry-dingtalk.git
pip install -e .

do you config dingtalk robot of your project? you can config by the following steps:
1. enable dingtalk of your project.
![dingtalk 1](https://user-images.githubusercontent.com/3305041/28909883-f2285a86-785c-11e7-8687-210d332a2111.png)

2. config dingtalk robot url of your project:
![ding 2](https://user-images.githubusercontent.com/3305041/28909887-f4c6bee0-785c-11e7-9ce8-f1e992a26963.png)

3. config by dingtalk alert:
![dingtalk3](https://user-images.githubusercontent.com/3305041/28909894-fa15b446-785c-11e7-90cc-be861305c6cb.png)
