### ISSUE TITLE
After installation, the current plug-in can not be found

### ISSUE THREAD

**Issue by einsqing** [gzhappysky/sentry-dingtalk#4]
After installation, the current plug-in can not be found

sentry：9.0.0

**Comment by Asenwang** [comment]
> After installation, the current plug-in can not be found
> 
> sentry：9.0.0

hi,我最近在安装sentry的时候也遇到这个问题。解决方案如下：

1. 安装插件
sentry upgrade
2. 如果2中有报错，请解决错误先。
我这边的错误是“Failed to load plugin 'dingding'” ... "ContextualVersionConflict: (redis 2.10.5 (/usr/local/lib/python2.7/site-packages), Requirement.parse('redis>=2.10.6'), set(['redis-py-cluster']))"
3. 更新redis-py-cluster
运行： pip install redis-py-cluster==1.3.4
4. sentry upgrade完美解决
